[package]
name = "buddle-utils"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
description = "Commonly shared code for the Buddle project"
license = "GPL-2.0"
edition = "2021"

[dependencies]
tracing = "0.1"
ux = "0.1"
