[package]
name = "buddle"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
license = "GPL-2.0"
repository = "https://github.com/buddle-org/buddle.git"
edition = "2021"

[dependencies]
